name: gym

services:
  gym-discovery-server:
    container_name: gym-discovery-server
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://gym-config-server:8888
      - SPRING_CLOUD_CONFIG_FAIL_FAST=true
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - gym-network
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

networks:
  gym-network:
    external: true
